import type { TextStats, TopWord } from "./types";

const wordsPerMinute = 200;

const stopWords = new Set([
  "a",
  "about",
  "above",
  "after",
  "again",
  "against",
  "all",
  "am",
  "an",
  "and",
  "any",
  "are",
  "as",
  "at",
  "be",
  "because",
  "been",
  "before",
  "being",
  "below",
  "between",
  "both",
  "but",
  "by",
  "can",
  "could",
  "did",
  "do",
  "does",
  "doing",
  "down",
  "during",
  "each",
  "few",
  "for",
  "from",
  "further",
  "had",
  "has",
  "have",
  "having",
  "he",
  "her",
  "here",
  "hers",
  "herself",
  "him",
  "himself",
  "his",
  "how",
  "i",
  "if",
  "in",
  "into",
  "is",
  "it",
  "its",
  "itself",
  "just",
  "me",
  "more",
  "most",
  "my",
  "myself",
  "no",
  "nor",
  "not",
  "now",
  "of",
  "off",
  "on",
  "once",
  "only",
  "or",
  "other",
  "our",
  "ours",
  "ourselves",
  "out",
  "over",
  "own",
  "same",
  "she",
  "should",
  "so",
  "some",
  "such",
  "than",
  "that",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "there",
  "these",
  "they",
  "this",
  "those",
  "through",
  "to",
  "too",
  "under",
  "until",
  "up",
  "very",
  "was",
  "we",
  "were",
  "what",
  "when",
  "where",
  "which",
  "while",
  "who",
  "whom",
  "why",
  "will",
  "with",
  "would",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "aber",
  "als",
  "also",
  "am",
  "an",
  "auch",
  "auf",
  "aus",
  "bei",
  "bin",
  "bis",
  "bist",
  "da",
  "damit",
  "dann",
  "das",
  "dass",
  "dein",
  "deine",
  "dem",
  "den",
  "denn",
  "der",
  "des",
  "dich",
  "die",
  "dies",
  "diese",
  "dieser",
  "dieses",
  "dir",
  "doch",
  "du",
  "ein",
  "eine",
  "einem",
  "einen",
  "einer",
  "eines",
  "er",
  "es",
  "euch",
  "euer",
  "für",
  "hat",
  "hatte",
  "hatten",
  "hier",
  "ich",
  "ihm",
  "ihn",
  "ihnen",
  "ihr",
  "ihre",
  "im",
  "in",
  "ist",
  "ja",
  "jede",
  "jedem",
  "jeden",
  "jeder",
  "jedes",
  "kann",
  "kein",
  "keine",
  "mit",
  "mich",
  "mir",
  "nach",
  "nicht",
  "noch",
  "nur",
  "oder",
  "sich",
  "sie",
  "sind",
  "so",
  "um",
  "und",
  "uns",
  "unser",
  "unter",
  "vom",
  "von",
  "vor",
  "war",
  "waren",
  "was",
  "weil",
  "wenn",
  "wer",
  "wie",
  "wir",
  "wird",
  "wo",
  "zu",
  "zum",
  "zur",
  "über",
]);

export function analyzeText(text: string): TextStats {
  const trimmed = text.trim();
  const words = tokenizeWords(text);
  const contentWords = words.filter((word) => !stopWords.has(word) && word.length > 1);
  const sentences = countSentences(trimmed);
  const paragraphs = trimmed ? trimmed.split(/\n\s*\n/).filter((paragraph) => paragraph.trim()).length : 0;
  const lines = text ? text.split(/\r\n|\r|\n/).length : 0;
  const charactersNoSpaces = text.replace(/\s/g, "").length;
  const topWords = getTopWords(contentWords, Math.max(1, words.length));

  return {
    words: words.length,
    uniqueWords: new Set(words).size,
    characters: text.length,
    charactersNoSpaces,
    sentences,
    paragraphs,
    lines,
    readingMinutes: words.length ? Math.max(1, Math.ceil(words.length / wordsPerMinute)) : 0,
    averageWordsPerSentence: sentences ? roundOne(words.length / sentences) : 0,
    averageCharactersPerWord: words.length ? roundOne(charactersNoSpaces / words.length) : 0,
    lexicalDensity: words.length ? Math.round((new Set(contentWords).size / words.length) * 100) : 0,
    topWords,
  };
}

function tokenizeWords(text: string): string[] {
  return text
    .toLocaleLowerCase("de-CH")
    .match(/[\p{L}\p{N}]+(?:['-][\p{L}\p{N}]+)*/gu) ?? [];
}

function countSentences(text: string): number {
  if (!text) return 0;
  const matches = text.match(/[^.!?\n]+[.!?]+(?:\s|$)|[^.!?\n]+$/g) ?? [];
  return matches.filter((sentence) => /[\p{L}\p{N}]/u.test(sentence)).length;
}

function getTopWords(words: string[], totalWords: number): TopWord[] {
  const counts = new Map<string, number>();
  for (const word of words) counts.set(word, (counts.get(word) ?? 0) + 1);

  return Array.from(counts.entries())
    .map(([word, count]) => ({
      word,
      count,
      percentage: roundOne((count / totalWords) * 100),
    }))
    .sort((a, b) => b.count - a.count || a.word.localeCompare(b.word))
    .slice(0, 12);
}

function roundOne(value: number): number {
  return Math.round(value * 10) / 10;
}
